port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  prefer-h3: false
  listen: 0.0.0.0:1053
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 11.0.0.0/8
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - "*.staruniongame.com"
    - "*.seaart.ai"
  nameserver-policy:
    +.staruniongame.com: 172.16.10.10
    +.seaart.dev: 172.16.10.10
    +.baidu.com: 119.29.29.29
    +.internal.crop.com: 10.0.0.1
    geosite:cn: https://doh.pub/dns-query
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - tls://8.8.4.4
    - tls://1.1.1.1
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    direct-nameserver:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com

